// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApp2.Data;

#nullable disable

namespace ProductsApp2.Migrations
{
    [DbContext(typeof(ProductsAppDbContext))]
    [Migration("20240619184158_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsApp2.Models.Domains.Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a5c4d3c-6043-49c5-a3f6-5a4c45127b1b"),
                            ProductDescription = "Fresh red apples",
                            ProductImageUrl = "https://example.com/apple.jpg",
                            ProductName = "Apple",
                            ProductPrice = 1.2
                        },
                        new
                        {
                            Id = new Guid("d642480d-71a5-491e-8f91-c525ebbbc55d"),
                            ProductDescription = "Ripe bananas",
                            ProductImageUrl = "https://example.com/banana.jpg",
                            ProductName = "Banana",
                            ProductPrice = 0.80000000000000004
                        },
                        new
                        {
                            Id = new Guid("8726df8a-8b98-4790-a657-42f72d36c711"),
                            ProductDescription = "Juicy oranges",
                            ProductImageUrl = "https://example.com/orange.jpg",
                            ProductName = "Orange",
                            ProductPrice = 1.5
                        },
                        new
                        {
                            Id = new Guid("5f9ca34e-2943-4b78-b9a3-34a0614ef227"),
                            ProductDescription = "1 litre of whole milk",
                            ProductImageUrl = "https://example.com/milk.jpg",
                            ProductName = "Milk",
                            ProductPrice = 1.0
                        },
                        new
                        {
                            Id = new Guid("c96b1755-5bfe-441d-b423-85a94df5045c"),
                            ProductDescription = "Whole grain bread",
                            ProductImageUrl = "https://example.com/bread.jpg",
                            ProductName = "Bread",
                            ProductPrice = 1.1000000000000001
                        },
                        new
                        {
                            Id = new Guid("8819ca40-5dc2-457b-b738-c1bfe1489fcc"),
                            ProductDescription = "Cheddar cheese",
                            ProductImageUrl = "https://example.com/cheese.jpg",
                            ProductName = "Cheese",
                            ProductPrice = 2.5
                        },
                        new
                        {
                            Id = new Guid("fce725c8-54c8-4292-bb25-ee35101e814f"),
                            ProductDescription = "Salted butter",
                            ProductImageUrl = "https://example.com/butter.jpg",
                            ProductName = "Butter",
                            ProductPrice = 1.8
                        },
                        new
                        {
                            Id = new Guid("dd829339-d0ad-4887-bf2b-a060d528d6f4"),
                            ProductDescription = "A dozen eggs",
                            ProductImageUrl = "https://example.com/eggs.jpg",
                            ProductName = "Eggs",
                            ProductPrice = 2.0
                        },
                        new
                        {
                            Id = new Guid("52bada25-0165-4489-bdb1-aeaf45a579d7"),
                            ProductDescription = "Natural yogurt",
                            ProductImageUrl = "https://example.com/yogurt.jpg",
                            ProductName = "Yogurt",
                            ProductPrice = 0.90000000000000002
                        },
                        new
                        {
                            Id = new Guid("9edebc18-5288-4e00-ae65-b9ef47d0e177"),
                            ProductDescription = "Fresh tomatoes",
                            ProductImageUrl = "https://example.com/tomato.jpg",
                            ProductName = "Tomato",
                            ProductPrice = 1.3
                        },
                        new
                        {
                            Id = new Guid("e7af36fd-7a29-4ece-a2bf-a24f7592f170"),
                            ProductDescription = "Organic carrots",
                            ProductImageUrl = "https://example.com/carrot.jpg",
                            ProductName = "Carrot",
                            ProductPrice = 1.0
                        },
                        new
                        {
                            Id = new Guid("b700e3ca-9ccb-4eb1-8bca-44d7755fb3a0"),
                            ProductDescription = "Fresh potatoes",
                            ProductImageUrl = "https://example.com/potato.jpg",
                            ProductName = "Potato",
                            ProductPrice = 0.69999999999999996
                        },
                        new
                        {
                            Id = new Guid("f831a1ff-68a3-4f57-a202-c2db685d727c"),
                            ProductDescription = "Green lettuce",
                            ProductImageUrl = "https://example.com/lettuce.jpg",
                            ProductName = "Lettuce",
                            ProductPrice = 1.2
                        },
                        new
                        {
                            Id = new Guid("2de2b713-e287-4572-9d69-7167522a9894"),
                            ProductDescription = "Boneless chicken breast",
                            ProductImageUrl = "https://example.com/chicken.jpg",
                            ProductName = "Chicken Breast",
                            ProductPrice = 5.0
                        },
                        new
                        {
                            Id = new Guid("f8fa3c1b-f100-4a56-b8c3-1aa6309fa908"),
                            ProductDescription = "Fresh salmon fillets",
                            ProductImageUrl = "https://example.com/salmon.jpg",
                            ProductName = "Salmon",
                            ProductPrice = 10.0
                        },
                        new
                        {
                            Id = new Guid("867810b4-892b-4c8c-a061-56f6775bc875"),
                            ProductDescription = "Italian pasta",
                            ProductImageUrl = "https://example.com/pasta.jpg",
                            ProductName = "Pasta",
                            ProductPrice = 1.5
                        },
                        new
                        {
                            Id = new Guid("35f6d981-8227-43fa-b12d-170c16129f37"),
                            ProductDescription = "Basmati rice",
                            ProductImageUrl = "https://example.com/rice.jpg",
                            ProductName = "Rice",
                            ProductPrice = 1.3
                        },
                        new
                        {
                            Id = new Guid("55d7d402-0e9d-409c-9211-b5cbb18eb8b3"),
                            ProductDescription = "Extra virgin olive oil",
                            ProductImageUrl = "https://example.com/oliveoil.jpg",
                            ProductName = "Olive Oil",
                            ProductPrice = 4.0
                        },
                        new
                        {
                            Id = new Guid("5f980d5e-5ded-4123-8261-497a9c9c4ae5"),
                            ProductDescription = "Sea salt",
                            ProductImageUrl = "https://example.com/salt.jpg",
                            ProductName = "Salt",
                            ProductPrice = 0.5
                        },
                        new
                        {
                            Id = new Guid("6dde3239-dddf-47cc-88f3-d682865f0d49"),
                            ProductDescription = "Black pepper",
                            ProductImageUrl = "https://example.com/pepper.jpg",
                            ProductName = "Pepper",
                            ProductPrice = 0.69999999999999996
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
